name: Deployment Marker
on:
  workflow_dispatch:
    branches:
      - main
  release:
    types: [published]

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic Deployment Marker
    steps:
      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Create Tracking Marker
        uses: newrelic/deployment-marker-action@v2.5.0
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID_CP }}
          version: "${{ env.RELEASE_VERSION }}"
          commit: "${{ github.sha }}"
          region: "EU"
          description: "Automated Release via Github Actions"
          deploymentType: "ROLLING"
          user: "${{ github.actor }}"